apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-apps
  namespace: openshift-gitops
spec:
  description: "Application deployments for all stages"
  sourceRepos:
    - '*'
  destinations:
    - namespace: demo-*
      server: https://kubernetes.default.svc
