resources:
- pvc.yaml
- sampleapl-demo-pipeline.yaml
- innerloop-binding.yaml
- innerloop-template.yaml
- outerloop-binding.yaml
- outerloop-template.yaml
- sampleapl-listener.yaml
- service.yaml
- route.yaml
