resources:
  - pvc.yaml
  - python-test-task.yaml
  - sampleapl-demo-pipeline.yaml
  - innerloop-binding.yaml
  - innerloop-template.yaml
  - outerloop-binding.yaml
  - outerloop-template.yaml
  - sampleapl-listener.yaml
  - service.yaml
  - route.yaml
  - update-manifest-pipeline.yaml
  - release-demo-binding.yaml
  - release-demo-listener.yaml
  - release-demo-template.yaml
  - trivy-scan-task.yaml
  - vuln-report-task.yaml
  - wait-argocd-rollout-task.yaml
  - playwright-task.yaml
  - patch-demo-pipeline.yaml
  - patch-demo-binding.yaml
  - patch-demo-template.yaml
  - patch-demo-listener.yaml
  - patch-demo-rbac.yaml
