apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sampleapl-demo-pipeline
spec:
  params:
    - default: 'https://github.com/kforetas/sampleapl-demo.git'
      description: アプリのソースコードリポジトリ
      name: repo-url
      type: string
    - default: rhnconsultingkemori
      description: docker hub username
      name: docker-username
      type: string
    - default: 'https://github.com/kforetas/sampleapl-demo-manifest.git'
      description: マニフェスト管理用リポジトリ
      name: manifest-repo-url
      type: string
    - default: latest
      description: ビルドするイメージのタグ
      name: image-tag
      type: string
    - default: dev
      description: 環境
      name: target-env
      type: string
  tasks:
    - name: prepare-tag
      params:
        - name: raw-tag
          value: $(params.image-tag)
      taskSpec:
        metadata: {}
        params:
          - name: raw-tag
            type: string
        results:
          - name: clean-tag
            type: string
        spec: null
        steps:
          - computeResources: {}
            image: alpine
            name: sanitize
            script: |
              # refs/tags/ を取り除いて result に書き出す

              CLEAN=$(echo "$(params.raw-tag)" | sed 's|refs/tags/||' | sed 's|refs/heads/||')

              echo -n "${CLEAN}" > $(results.clean-tag.path)
    - name: git-clone-source
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: source
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: $(params.repo-url)
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-data
    - name: buildah
      params:
        - name: IMAGE
          value: 'docker.io/$(params.docker-username)/sampleapl-demo:$(tasks.prepare-tag.results.clean-tag)'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: BUILD_ARGS
          value:
            - ''
        - name: CONTEXT
          value: source
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - prepare-tag
        - git-clone-source
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: shared-data
    - name: git-clone-manifest
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: manifest
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'false'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: $(params.manifest-repo-url)
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: shared-data
    - name: update-gitops
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'false'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: GIT_USER_NAME
          value: kforetas
        - name: GIT_USER_EMAIL
          value: kforetxp@yahoo.co.jp
        - name: GIT_SCRIPT
          value: |-
            # 1. 開発環境（dev）のディレクトリへ移動 
            cd $(workspaces.source.path)/manifest/manifest
            # パラメータ target-env が "prod" なら overlays/prod を、そうでなければ dev を更新
            TARGET_DIR="overlays/$(params.target-env)"
            cd $TARGET_DIR
            # 2. kustomization.yaml 内の newTag の行だけを置換 
            sed -i "s|newTag:.*|newTag: $(tasks.prepare-tag.results.clean-tag)|g" kustomization.yaml
            # 3. Git Push 
            git add . 
            git commit -m "Update $(params.target-env) image to $(tasks.prepare-tag.results.clean-tag)" 
            git push origin HEAD:main
      runAfter:
        - buildah
        - git-clone-manifest
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-cli
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: shared-data
  workspaces:
    - name: shared-data
