apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sampleapl-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: innerloop-binding
      interceptors:
        - params:
            - name: filter
              value: |
                header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/main'
          ref:
            kind: ClusterInterceptor
            name: cel
      name: branch-push-trigger
      template:
        ref: innerloop-template
    - bindings:
        - kind: TriggerBinding
          ref: outerloop-binding
      interceptors:
        - params:
            - name: filter
              value: |
                header.match('X-GitHub-Event', 'push') && body.ref.startsWith('refs/tags/')
          ref:
            kind: ClusterInterceptor
            name: cel
      name: tag-push-trigger
      template:
        ref: outerloop-template
