apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: release-demo-pipeline
  namespace: tekton-demo
spec:
  params:
    - name: target-env
      default: prod
      type: string
    - name: new-tag
      default: v1.2.2
      type: string
    - name: manifest-repo-url
      default: 'https://github.com/kforetas/sampleapl-demo-manifest.git'
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: git-clone-manifest
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: URL
          value: $(params.manifest-repo-url)
        - name: REVISION
          value: main
        - name: SUBDIRECTORY
          value: "manifest"
        - name: DELETE_EXISTING
          value: 'true'
      workspaces:
        - name: output
          workspace: shared-data

    - name: update-yaml
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-cli
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      runAfter:
        - git-clone-manifest
      params:
        - name: DELETE_EXISTING
          value: 'false'
        - name: GIT_USER_NAME
          value: kforetas
        - name: GIT_USER_EMAIL
          value: kforetxp@yahoo.co.jp
        - name: GIT_SCRIPT
          value: |-
            cd $(workspaces.source.path)/manifest/manifest
            TARGET_DIR="overlays/$(params.target-env)"
            cd $TARGET_DIR
            sed -i "s|newTag:.*|newTag: $(params.new-tag)|g" kustomization.yaml
            git add . 
            git commit -m "Update $(params.target-env) image to $(params.new-tag)" 
            git push origin HEAD:main
      workspaces:
        - name: source
          workspace: shared-data