apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: release-demo-pipeline
  namespace: tekton-demo
spec:
  params:
    - name: target-env
      default: prod
      type: string
    - name: new-tag
      default: v1.2.2
      type: string
    - name: manifest-repo-url
      default: 'https://github.com/kforetas/sampleapl-demo-manifest.git'
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: git-clone-manifest
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: URL
          value: $(params.manifest-repo-url)
        - name: REVISION
          value: main
        - name: SUBDIRECTORY
          value: "manifest"
        - name: DELETE_EXISTING
          value: 'true'
      workspaces:
        - name: output
          workspace: shared-data

    - name: update-yaml
      taskRef:
        name: update-manifest
      runAfter:
        - git-clone-manifest
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: target-env
          value: $(params.target-env)
        - name: new-tag
          value: $(params.new-tag)
