apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: release-demo-pipeline
  namespace: tekton-demo
spec:
  params:
    - name: target-env
    - name: new-tag
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "https://github.com/kforetas/sampleapl-demo-manifest.git"
    - name: update-yaml
      taskRef:
        name: update-manifest
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: target-env
          value: $(params.target-env)
        - name: new-tag
          value: $(params.new-tag)
