apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapl-demo
  labels:
    app: sampleapl-demo
    app.openshift.io/runtime: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapl-demo
  template:
    metadata:
      labels:
        app: sampleapl-demo
    spec:
      containers:
        - name: sampleapl-demo
          image: docker.io/rhnconsultingkemori/sampleapl-demo:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8088
              protocol: TCP
