resources:
  - ../../base

# Commit sync - commit_hash_tag
images:
  - name: docker.io/rhnconsultingkemori/sampleapl-demo
    newName: docker.io/rhnconsultingkemori/sampleapl-demo
    newTag: e923d63f63b0c7325183eb376abd230561adccb3
