resources:
  - ../../base

# Commit sync - commit_hash_tag
images:
  - name: docker.io/rhnconsultingkemori/sampleapl-demo
    newName: docker.io/rhnconsultingkemori/sampleapl-demo
    newTag: ce4d990933188a3621e07672012f2ad7cbc36312
