resources:
  - ../../../base

# Commit sync - commit_hash_tag
images:
  - name: docker.io/rhnconsultingkemori/sampleapl-demo
    newName: docker.io/rhnconsultingkemori/sampleapl-demo
    newTag: beb83aaabfa672c1492c8f93b685b501614006f7
