apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-sampleapl-demo-itst-2
  namespace: openshift-gitops
spec:
  project: project-apps
  source:
    repoURL: 'https://github.com/kforetas/sampleapl-demo-manifest'
    targetRevision: HEAD
    path: manifest/overlays/itst-2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-itst-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
